DigitalYou-CarRentalApp/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post 'cars/new', to: 'cars#create'
  post "cars/:id/edit", to:"cars#update"
  post 'users/new', to: 'users#create'
  post "users/:id/edit", to:"users#update"
  post 'bookings/new', to: 'bookings#create'
  
  
  resources :cars
  resources :users
  resources :bookings
end

DigitalYou-CarRentalApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

DigitalYou-CarRentalApp/app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :start_date, :end_date, presence: true
  validate :user_id
  validate :car_id
  validate :validate_date_after_start_date
  validate :validate_booking

  private

  def validate_date_after_start_date
    return if end_date.nil? || start_date.nil?

    if end_date < start_date
      errors.add(:end_date, 'must be after the start date')
    end
  end

  def validate_booking
    booking_exist = Booking.where("DATE(end_date) > DATE('now') and user_id = ?", user_id)
    
    unless booking_exist.empty?
      errors.add(:end_date, 'reservation limit exceeded')
    end
  end
end

DigitalYou-CarRentalApp/app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  has_many :bookings

  validates_presence_of :gearshift, :AC
  validates :name, presence: true, length: { minimum: 1, maximum: 50 }
  validates :type_options, presence: true, length: { minimum: 1, maximum: 50 }
  validates :image, presence: true
  validates :price_hour, presence: true, numericality: { only_float: true, greater_than_or_equal_to: 10, less_than_or_equal_to: 100 }
  validates :doors, presence: true, numericality: { only_interger: true, greater_than_or_equal_to: 2, less_than_or_equal_to: 6 }
  validates :luggage, presence: true, numericality: { only_float: true, greater_than_or_equal_to: 10, less_than_or_equal_to: 30 }
  validates :pick_up_location, presence: true, length: { minimum: 1, maximum: 500 }
end

DigitalYou-CarRentalApp/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :bookings

  validates :first_name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :last_name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :age, presence: true, numericality: { only_interger: true, greater_than_or_equal_to: 18, less_than_or_equal_to: 90 }
  validates :city, presence: true, length: { minimum: 1, maximum: 30 }
end

DigitalYou-CarRentalApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Response
  include ExceptionHandler
end

DigitalYou-CarRentalApp/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # frozen_string_literal: true
  # GET /bookings
  require 'user'
  def index
    @bookings = Booking.all
    #json_response(@bookings)
  end

  def new
    @booking = Booking.new
  end

  # POST /bookings

  def create
    @booking = Booking.create!(booking_params)
    print @booking.save ? 'user saved on db' : 'user dont saved on bd'
    #json_response(@user, :created)
    render 'show'
  end

  # GET /bookings/:id

  def show
    @booking = Booking.find(params[:id])
    #json_response(@booking)
  end

  # PUT /bookings/:id

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(bookings_params)
      redirect_to @booking
      print  @booking.save ? 'bookings edited and saved on db' : 'bookings dont saved on bd'
    else
      render 'edit'
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  # DELETE /bookings/:id

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to '/bookings'
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :car_id)
  end

  def set_bookings
    @booking = Booking.find(params[:id])
  end

end

DigitalYou-CarRentalApp/app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController
  # GET /cars
  def index
    @cars = Car.all
    #json_response(@cars)
  end

  def new
    @cars = Car.new
  end

  # POST /cars

  def create
    @car = Car.create!(car_params)
    print @car.save ? 'car saved on db' : 'card dont saved on bd'
    #json_response(@car, :created)
    render 'show'
  end

  # GET /cars/:id

  def show
    @car = Car.find(params[:id])
    #json_response(@car)
  end

  # PUT /cars/:id

  def update
    @car = Car.find(params[:id])
    if @car.update(car_params)
      redirect_to @car
      print @car.save ? 'car edited and saved on db' : 'card dont saved on bd'
    else
      render 'edit'
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  # DELETE /cars/:id

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to '/cars'
  end

  private

  def car_params
    params.require(:car).permit(:name, :image, :type_options, :price_hour, :doors, :gearshift, :AC, :luggage, :pick_up_location)
  end

  def set_car
    @car = Car.find(params[:id])
  end
end

DigitalYou-CarRentalApp/app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  # provides the more graceful `included` method
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

DigitalYou-CarRentalApp/app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

DigitalYou-CarRentalApp/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  # GET /users
  def index
    @users = User.all
    #json_response(@users)
  end

  def new
    @users = User.new
  end

  # POST /users

  def create
    @user = User.create!(user_params)
    print @user.save ? 'user saved on db' : 'user dont saved on bd'
    #json_response(@user, :created)
    render 'show'
  end

  # GET /users/:id

  def show
    @user = User.find(params[:id])
    #json_response(@user)
  end

  # PUT /user/:id

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
      print @user.save ? 'user edited and saved on db' : 'user dont saved on bd'
    else
      render 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  # DELETE /user/:id

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/users'
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :city)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

DigitalYou-CarRentalApp/app/helpers/application_helper.rb
module ApplicationHelper
end

DigitalYou-CarRentalApp/app/helpers/bookings_helper.rb
module BookingsHelper
end

DigitalYou-CarRentalApp/app/helpers/cars_helper.rb
module CarsHelper
end

DigitalYou-CarRentalApp/app/helpers/users_helper.rb
module UsersHelper
end

DigitalYou-CarRentalApp/app/views/bookings/_form.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <p>Haz tu reserva</p>
        <%= form_for :booking do |form| %>
          <p>
            <%= form.label :user_id %><br>
            <%= form.collection_select :user_id, User.all, :id, :first_name %>
          </p>
          <p>
            <%= form.label :car_id %><br>
            <%= form.collection_select :car_id, Car.all, :id, :name %>
          </p>
          <p>
            <%= form.label 'start_time', 'Start time' %>
            <%= form.datetime_select :start_date, { minute_step: 15 } %>
          </p>
          <p>
            <%= form.label 'end_time', 'end time' %>
            <%= form.datetime_select :end_date, { minute_step: 15 } %>
          </p>
          <div class="buttons-form">
            <%= form.submit 'Reserva Car',class:"btn btn-success w-50 my-3"%>
            <%= link_to 'Go back all Bookings', bookings_path,class:"btn btn-secondary w-50 my-3"%>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-3"></div>
  </div>
</div>

DigitalYou-CarRentalApp/app/views/bookings/exception.html.erb
<p>Cant created booking<p>

DigitalYou-CarRentalApp/app/views/bookings/index.html.erb
<h1 class="text-center my-5">All bookings</h1>
<div class="container">
  <div class="row">
    <% @bookings.each do | booking | %>
      <div class="col-4 mt-5">
        <div class="card">
          <h3 class="text-center my-3">Booking ID <%=booking.id%><h3>
          <h3 class="text-center my-3">User ID <%=booking.user_id%><h3>
          <p class="text-center my-3">Booking user: <%=label :first_name, @user = User.find(booking.user_id), @user.first_name %><p>
          <h3>Car ID <%=booking.car_id%><h3>
          <p class="text-center my-3">Booking car: <%=label :name, @car = Car.find(booking.car_id), @car.name %><p>
          <div class="card-body text-center">
            <div class="d-flex flex-column align-items-center">
              <%= link_to 'Delete Booking', booking_path(booking), :method => :delete, data: {:confirm => "You sure?" },class:"btn btn-danger w-50 my-3" %></div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

              

DigitalYou-CarRentalApp/app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

DigitalYou-CarRentalApp/app/views/bookings/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <h3 class="card-title">Booking</h3>
        <h3 class="text-center my-3">Booking ID <%=@booking.id%><h3>
        <%= link_to 'Go back all bookings', bookings_path,class:"btn btn-secondary w-50 my-3"%>
      </div>
    </div>
      <div class="col-3"></div>
  </div>
</div>

DigitalYou-CarRentalApp/app/views/cars/_form.html.erb
  
<div class="container">
  <div class="row mt-5">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <%= form_for :car do |form| %>
          <p>
            <%= form.label :name %><br>
            <%= form.text_area :name %>
          </p>
          <p>
            <%= form.label :image %><br>
            <%= form.text_field :image %>
          </p>
          <p>
            <%= form.label :type_options %><br>
            <%= form.text_area :type_options %>
          </p>
          <p>
            <%= form.label :price_hour %><br>
            <%= form.number_field :price_hour %>
          </p>
          <p>
            <%= form.label :doors %><br>
            <%= form.number_field :doors %>
          </p>
          <p>
            <%= form.label :gearshift %><br>
            <%= form.text_area :gearshift %>
          </p>
          <p>
            <%= form.label :AC %><br>
            <%= form.text_area :AC %>
          </p>
          <p>
            <%= form.label :luggage %><br>
            <%= form.number_field :luggage %> kg
          </p>
          <p>
            <%= form.label :pick_up_location %><br>
            <%= form.text_area :pick_up_location %>
          </p>
          <p>
            <div class="buttons-form">
              <% if (request.path).include? 'edit'%>
                <%= form.submit 'Edit Car',class:"btn btn-success w-50 my-3"%>
              </div>
            <% else %>
              <%= form.submit 'Create Car',class:"btn btn-success w-50 my-3"%>
            <%end%>
            <%= link_to 'Go back all cars', cars_path,class:"btn btn-secondary w-50 my-3"%>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-3"></div>
  </div>
</div>

DigitalYou-CarRentalApp/app/views/cars/edit.html.erb
<h1>Edit Car</h1>

<%= render 'form' %>

DigitalYou-CarRentalApp/app/views/cars/index.html.erb
<h1 class="text-center my-5">Cars</h1>
<div class="container">
  <div class="row">
    <% @cars.each do | car | %>
      <div class="col-4 mt-5">
        <div class="card">
          <h1 class="text-center my-3"><%=car.name%></h1>
          <div class="card-body text-center">
            <h5 class="card-title"><%=car.name%></h5>
            <div class="d-flex flex-column align-items-center">
              <%= link_to 'Show Car', car_path(car),class:"btn btn-primary w-50"%>
              <%= link_to 'Edit Car', edit_car_path(car),class:"btn btn-warning w-50 my-3"%>
              <%= link_to 'Delete Car', car_path(car), :method => :delete, data: {:confirm => "You sure?" },class:"btn btn-danger w-50" %></div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

DigitalYou-CarRentalApp/app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

DigitalYou-CarRentalApp/app/views/cars/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <%#img = ['bcn.jpg','mad','val','nike','natura','berlos'].sample%>
        <%#= image_tag img, {height: 200} %>
        <h3 class="card-title">Car</h3>
        <p><%= @car.name %></p>
        <h3 class="card-title">Options type:</h3>
        <p><%= @car.type_options %></p>
        <h3 class="card-title">Price type:</h3>
        <p><%= @car.type_options %></p>
        <h3 class="card-title">Doors:</h3>
        <p><%= @car.doors %></p>
        <h3 class="card-title">Gearshift:</h3>
        <p><%= @car.gearshift %></p>
        <h3 class="card-title">AC:</h3>
        <p><%= @car.AC %></p>
        <h3 class="card-title">Pick up location:</h3>
        <p><%= @car.pick_up_location %></p>
        <h3 class="card-title">Luggage:</h3>
        <p><%= @car.luggage %></p>
        <%= link_to 'Go back all cars', cars_path,class:"btn btn-secondary w-50 my-3"%>
      </div>
    </div>
    <div class="col-3"></div>
  </div>
</div>

DigitalYou-CarRentalApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "nav/nav" %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

DigitalYou-CarRentalApp/app/views/nav/_nav.html.erb
 <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
      <div class="container">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <%= link_to 'New User', new_user_path(@user),class:"btn btn-primary w-100"%>
            </li>
            <li class="nav-item active">
                <%= link_to 'All Users','/users',class:"btn btn-primary w-100"%>
            </li>
            <li class="nav-item">
                <%= link_to 'New Car', new_car_path(@car),class:"btn btn-primary w-100"%>
            </li>  
            <li class="nav-item">
                <%= link_to 'All Cars','/cars',class:"btn btn-primary w-100"%>
            </li>  
            <li class="nav-item">
                <%= link_to 'New Booking',new_booking_path(@booking),class:"btn btn-primary w-100"%>
            </li>
            <li class="nav-item">
                <%= link_to 'All Bookings','/bookings',class:"btn btn-primary w-100"%>
            </li>              
        </ul>
      </div>  
 </nav>

DigitalYou-CarRentalApp/app/views/users/_form.html.erb
  
<div class="container">
  <div class="row mt-5">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <%= form_for :user do |form| %>
          <p>
            <%= form.label :first_name %><br>
            <%= form.text_field :first_name %>
          </p>
          <p>
            <%= form.label :last_name %><br>
            <%= form.text_field :last_name %>
          </p>
          <p>
            <%= form.label :age %><br>
            <%= form.number_field :age %>
          </p>
          <p>
            <%= form.label :city %><br>
            <%= form.text_field :city %>
          </p>
          <div class="buttons-form">
            <% if (request.path).include? 'edit'%>
              <%= form.submit 'Edit User',class:"btn btn-success w-50 my-3"%>
            </div>
          <% else %>
            <%= form.submit 'Create User',class:"btn btn-success w-50 my-3"%>
          <%end%>
          <%= link_to 'Go back all cars', cars_path,class:"btn btn-secondary w-50 my-3"%>
        </div>
      <% end %>
    </div>
    <div class="col-3"></div>
  </div>
</div>

DigitalYou-CarRentalApp/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

DigitalYou-CarRentalApp/app/views/users/index.html.erb
<h1 class="text-center my-5">All Users</h1>
<div class="container">
  <div class="row">
    <% @users.each do | user | %>
      <div class="col-4 mt-5">
        <div class="card">
          <h1 class="text-center my-3"><%=user.first_name%></h1>
          <div class="card-body text-center">
            <h5 class="card-title"><%=user.last_name%></h5>
            <div class="d-flex flex-column align-items-center">
              <%= link_to 'Show User', user_path(user),class:"btn btn-primary w-50"%>
              <%= link_to 'Edit User', edit_user_path(user),class:"btn btn-warning w-50 my-3"%>
              <%= link_to 'Delete User', user_path(user), :method => :delete, data: {:confirm => "You sure?" },class:"btn btn-danger w-50" %></div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

DigitalYou-CarRentalApp/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

DigitalYou-CarRentalApp/app/views/users/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <h3 class="card-title">First Name</h3>
        <p><%= @user.first_name %></p>
        <h3 class="card-title">Last Name</h3>
        <p><%= @user.last_name %></p>
        <h3 class="card-title">Age:</h3>
        <p><%= @user.age %></p>
        <h3 class="card-title">City</h3>
        <p><%= @user.city %></p>
        <%= link_to 'Go back all users', users_path,class:"btn btn-secondary w-50 my-3"%>
      </div>
    </div>
    <div class="col-3"></div>
  </div>
</div>